trigger:
  branches:
    include:
      - main
  

pool:
  name: Azure Pipelines


steps:


- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ml-research-sc'
    appName: 'sgsddsdf'
    appType: webAppLinux
    package: '$(Build.ArtifactStagingDirectory)/drop/$(Build.BuildId).zip'